# Generated by Django 5.0.6 on 2024-08-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userbankaccount_is_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='is_bankrupt',
        ),
    ]
