# Generated by Django 5.0.6 on 2024-08-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_is_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_bankrupt',
        ),
    ]
